const talentDataMap = {
  alteri: {
    echoed_voice: {
      name_key:  "talent_alteri_echoed_voice-u",
      rule_text_key: "talent_alteri_echoed_voice_rules-u",
      skills: "",
	  affected_skill: "perform_impersonation",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    ghost_protocol: {
      name_key:  "talent_alteri_ghost_protocol-u",
      rule_text_key: "talent_alteri_ghost_protocol_rules-u",
      skills: "",
	  affected_skill: [ "slicing", "stealth" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    grace_of_the_many: {
      name_key:  "talent_alteri_grace_of_the_many-u",
      rule_text_key: "talent_alteri_grace_of_the_many_rules-u",
      skills: "",
	  affected_skill: [ "disguise", "insight", "stealth" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    maskwrights_grace: {
      name_key:  "talent_alteri_maskwrights_grace-u",
      rule_text_key: "talent_alteri_maskwrights_grace_rules-u",
      skills: [ "disguise", "insight", "perform_impersonation"  ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    reflexive_shift: {
      name_key:  "talent_alteri_reflexive_shift-u",
      rule_text_key: "talent_alteri_reflexive_shift_rules-u",
      skills: "",
	  affected_skill: [ "deception", "disguise" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "scene"
    },
    second_skin: {
      name_key:  "talent_alteri_second_skin-u",
      rule_text_key: "talent_alteri_second_skin_rules-u",
      skills: "",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    shaped_for_subtlety: {
      name_key:  "talent_alteri_shaped_for_subtlety-u",
      rule_text_key: "talent_alteri_shaped_for_subtlety_rules-u",
      skills: [ "insight", "slicing", "stealth" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    social_chameleon: {
      name_key:  "talent_alteri_social_chameleon-u",
      rule_text_key: "talent_alteri_social_chameleon_rules-u",
      skills: "",
	  affected_skill: [ "charm", "deception", "persuade" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    whisper_touched: {
      name_key:  "talent_alteri_whisper_touched-u",
      rule_text_key: "talent_alteri_whisper_touched_rules-u",
      skills: "",
	  affected_skill: [ "magic_enchantment", "magic_illusion" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    adaptive_memory: {
      name_key:  "talent_alteri_adaptive_memory-u",
      rule_text_key: "talent_alteri_adaptive_memory_rules-u",
      skills: "",
	  affected_skill: [ "deception", "perform_impersonation" ],
      prerequisite: [ "maskwrights_grace", "social_chameleon" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    deep_mask_integration: {
      name_key:  "talent_alteri_deep_mask_integration-u",
      rule_text_key: "talent_alteri_deep_mask_integration_rules-u",
      skills: [ "disguise", "insight" ],
      prerequisite: [ "second_skin" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: ""
    },
    facial_recalibration: {
      name_key:  "talent_alteri_facial_recalibration-u",
      rule_text_key: "talent_alteri_facial_recalibration_rules-u",
      skills: "",
	  affected_skill: [ "disguise", "perform_impersonation" ],
      prerequisite: [ "echoed_voice", "second_skin" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    ghost_signature: {
      name_key:  "talent_alteri_ghost_signature-u",
      rule_text_key: "talent_alteri_ghost_signature_rules-u",
      skills: "",
	  affected_skill: [ "electronics", "slicing" ],
      prerequisite: [ "ghost_protocol" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    mirror_weave: {
      name_key:  "talent_alteri_mirror_weave-u",
      rule_text_key: "talent_alteri_mirror_weave_rules-u",
      skills: "",
	  affected_skill: [ "magic_enchantment", "magic_illusion" ],
      prerequisite: [ "whisper_touched" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    persona_anchor: {
      name_key:  "talent_alteri_persona_anchor-u",
      rule_text_key: "talent_alteri_persona_anchor_rules-u",
      skills: [ "arcana", "perform_impersonation", "slicing" ],
      prerequisite: [ "grace_of_the_many" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: ""
    },
    shift_reflex: {
      name_key:  "talent_alteri_shift_reflex-u",
      rule_text_key: "talent_alteri_shift_reflex_rules-u",
      skills: "",
	  affected_skill: [ "dodge", "stealth" ],
      prerequisite: [ "reflexive_shift" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "scene"
    },
    silent_archive: {
      name_key:  "talent_alteri_silent_archive-u",
      rule_text_key: "talent_alteri_silent_archive_rules-u",
      skills: "",
      prerequisite: [ "deep_mask_integration" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    veil_echo_memory: {
      name_key:  "talent_alteri_veil_echo_memory-u",
      rule_text_key: "talent_alteri_veil_echo_memory_rules-u",
      skills: "",
	  affected_skill: [ "arcana", "insight", "occult_lore" ],
      prerequisite: [ "ghost_protocol", "whisper_touched" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    biometric_phantom: {
      name_key:  "talent_alteri_biometric_phantom-u",
      rule_text_key: "talent_alteri_biometric_phantom_rules-u",
      skills: "",
	  affected_skill: [ "electronics", "slicing" ],
      prerequisite: [ "ghost_signature" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    identity_cascade: {
      name_key:  "talent_alteri_identity_cascade-u",
      rule_text_key: "talent_alteri_identity_cascade_rules-u",
      skills: "",
	  affected_skill: [ "disguise", "insight" ],
      prerequisite: [ "deep_mask_integration" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "scene"
    },
    memory_graft: {
      name_key:  "talent_alteri_memory_graft-u",
      rule_text_key: "talent_alteri_memory_graft_rules-u",
      skills: "",
	  affected_skill: [ "arcana", "insight", "perform_impersonation" ],
      prerequisite: [ "deep_mask_integration" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    perfect_mimicry: {
      name_key:  "talent_alteri_perfect_mimicry-u",
      rule_text_key: "talent_alteri_perfect_mimicry_rules-u",
      skills: "",
	  affected_skill: [ "deception", "disguise" ],
	  affected_skill_group: "perform",
      prerequisite: [ "echoed_voice", "facial_recalibration" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    social_echo: {
      name_key:  "talent_alteri_social_echo-u",
      rule_text_key: "talent_alteri_social_echo_rules-u",
      skills: "",
	  affected_skill: [ "charm", "deception", "persuade" ],
      prerequisite: [ "adaptive_memory", "social_chameleon" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    veil_shaped_will: {
      name_key:  "talent_alteri_veil_shaped_will-u",
      rule_text_key: "talent_alteri_veil_shaped_will_rules-u",
      skills: "",
	  affected_skill: [ "magic_alteration", "magic_enchantment", "magic_illusion" ],
      prerequisite: [ "mirror_weave", "whisper_touched" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    author_of_the_lie: {
      name_key:  "talent_alteri_author_of_the_lie-u",
      rule_text_key: "talent_alteri_author_of_the_lie_rules-u",
      skills: "",
	  affected_skill: [ "deception", "disguise" ],
	  affected_skill_group: "perform",
      prerequisite: [ "deep_mask_integration", "social_echo" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    immaculate_impersonation: {
      name_key:  "talent_alteri_immaculate_impersonation-u",
      rule_text_key: "talent_alteri_immaculate_impersonation_rules-u",
      skills: "",
	  affected_skill: [ "disguise", "perform_impersonation", "slicing" ],
      prerequisite: [ "biometric_phantom", "perfect_mimicry" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    living_mask_archive: {
      name_key:  "talent_alteri_living_mask_archive-u",
      rule_text_key: "talent_alteri_living_mask_archive_rules-u",
      skills: "",
	  affected_skill: "stealth",
	  affected_skill_group: "social",
      prerequisite: [ "identity_cascade", "memory_graft" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    veil_mirroring_ritual: {
      name_key:  "talent_alteri_veil_mirroring_ritual-u",
      rule_text_key: "talent_alteri_veil_mirroring_ritual_rules-u",
      skills: "",
	  affected_skill: [ "magic_enchantment", "magic_illusion" ],
      prerequisite: [ "veil_shaped_will" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    }
  },
  draevi: {
    bone_sung_memory: {
        name_key: "talent_draevi_bone_sung_memory-u",
        rule_text_key: "talent_draevi_bone_sung_memory_rules-u",
        skills: "",
        prerequisite: "",
        tier: 1,
        cost: 10,
        capstone: false,
        usage_limit: "session"
    },
    clan_blooded: {
        name_key: "talent_draevi_clan_blooded-u",
        rule_text_key: "talent_draevi_clan_blooded_rules-u",
        skills: [ "intimidate", "survival_wilderness", "track" ],
        prerequisite: "",
        tier: 1,
        cost: 10,
        capstone: false,
        usage_limit: ""
    },
    gutter_stalker: {
        name_key: "talent_draevi_gutter_stalker-u",
        rule_text_key: "talent_draevi_gutter_stalker_rules-u",
        skills: "",
		affected_skill: "stealth",
        prerequisite: "",
        tier: 1,
        cost: 10,
        capstone: false,
        usage_limit: "session"
    },
    iron_stomach: {
        name_key: "talent_draevi_iron_stomach-u",
        rule_text_key: "talent_draevi_iron_stomach_rules-u",
        skills: "",
		affected_stat: "con",
        prerequisite: "",
        tier: 1,
        cost: 10,
        capstone: false,
        usage_limit: ""
    },
    scavengers_edge: {
        name_key: "talent_draevi_scavengers_edge-u",
        rule_text_key: "talent_draevi_scavengers_edge_rules-u",
        skills: [ "electronics", "mechanics", "streetwise" ],
        prerequisite: "",
        tier: 1,
        cost: 10,
        capstone: false,
        usage_limit: ""
    },
    silent_step_sharp_ear: {
        name_key: "talent_draevi_silent_step_sharp_ear-u",
        rule_text_key: "talent_draevi_silent_step_sharp_ear_rules-u",
        skills: "",
		affected_skill: [ "listen", "perception", "stealth" ],
        prerequisite: "",
        tier: 1,
        cost: 10,
        capstone: false,
        usage_limit: "scene"
    },
    spirits_in_stone: {
        name_key: "talent_draevi_spirits_in_stone-u",
        rule_text_key: "talent_draevi_spirits_in_stone_rules-u",
        skills: "",
		affected_skill: "spirit_lore",
        prerequisite: "",
        tier: 1,
        cost: 10,
        capstone: false,
        usage_limit: "session"
    },
    trailborn_reflexes: {
        name_key: "talent_draevi_trailborn_reflexes-u",
        rule_text_key: "talent_draevi_trailborn_reflexes_rules-u",
        skills: "",
		affected_skill: "dodge",
        prerequisite: "",
        tier: 1,
        cost: 10,
        capstone: false,
        usage_limit: "scene"
    },
    urban_climber: {
        name_key: "talent_draevi_urban_climber-u",
        rule_text_key: "talent_draevi_urban_climber_rules-u",
        skills: "",
		affected_skill: [ "athletics", "coordination" ],
        prerequisite: "",
        tier: 1,
        cost: 10,
        capstone: false,
        usage_limit: "session"
    },
    echo_binders_rite: {
        name_key: "talent_draevi_echo_binders_rite-u",
        rule_text_key: "talent_draevi_echo_binders_rite_rules-u",
        skills: "",
		affected_skill: [ "magic_summoning", "spirit_lore" ],
        prerequisite: [ "spirits_in_stone" ],
        tier: 2,
        cost: 20,
        capstone: false,
        usage_limit: "session"
    },
    hardened_trailwalker: {
        name_key: "talent_draevi_hardened_trailwalker-u",
        rule_text_key: "talent_draevi_hardened_trailwalker_rules-u",
        skills: "",
		affected_skill: [ "survival_urban" , "survival_wilderness" ],
        prerequisite: [ "iron_stomach", "trailborn_reflexes" ],
        tier: 2,
        cost: 20,
        capstone: false,
        usage_limit: "session"
    },
    instinctive_counter: {
        name_key: "talent_draevi_instinctive_counter-u",
        rule_text_key: "talent_draevi_instinctive_counter_rules-u",
        skills: "",
		affected_skill: "dodge",
		affected_skill_group: "combat_melee",
        prerequisite: [ "trailborn_reflexes" ],
        tier: 2,
        cost: 20,
        capstone: false,
        usage_limit: "scene"
    },
    root_stance_tenacity: {
        name_key: "talent_draevi_root_stance_tenacity-u",
        rule_text_key: "talent_draevi_root_stance_tenacity_rules-u",
        skills: "",
		affected_stat: [ "con", "str" ],
        prerequisite: [ "clan_blooded", "iron_stomach" ],
        tier: 2,
        cost: 20,
        capstone: false,
        usage_limit: "session"
    },
    scent_the_shift: {
        name_key: "talent_draevi_scent_the_shift-u",
        rule_text_key: "talent_draevi_scent_the_shift_rules-u",
        skills: "",
		affected_skill: [ "perception", "spirit_lore" ],
        prerequisite: [ "spirits_in_stone", "trailborn_reflexes" ],
        tier: 2,
        cost: 20,
        capstone: false,
        usage_limit: "session"
    },
    tales_etched_in_horn: {
        name_key: "talent_draevi_tales_etched_in_horn-u",
        rule_text_key: "talent_draevi_tales_etched_in_horn_rules-u",
        skills: "",
		affected_skill: [ "etiquette_draevi", "occult_lore", "spirit_lore" ],
        prerequisite: [ "clan_blooded" ],
        tier: 2,
        cost: 20,
        capstone: false,
        usage_limit: "session"
    },
    urban_tracker: {
        name_key: "talent_draevi_urban_tracker-u",
        rule_text_key: "talent_draevi_urban_tracker_rules-u",
        skills: "",
		affected_skill: [ "stealth", "streetwise", "track" ],
        prerequisite: [ "gutter_stalker" ],
        tier: 2,
        cost: 20,
        capstone: false,
        usage_limit: ""
    },
    veins_of_stone: {
        name_key: "talent_draevi_veins_of_stone-u",
        rule_text_key: "talent_draevi_veins_of_stone_rules-u",
        skills: "",
		affected_stat: "con",
        prerequisite: [ "clan_blooded", "iron_stomach" ],
        tier: 2,
        cost: 20,
        capstone: false,
        usage_limit: "session"
    },
    ancestors_pulse: {
        name_key: "talent_draevi_ancestors_pulse-u",
        rule_text_key: "talent_draevi_ancestors_pulse_rules-u",
        skills: "",
		affected_skill: [ "magic_summoning", "spirit_lore" ],
        prerequisite: [ "tales_etched_in_horn" ],
        tier: 3,
        cost: 30,
        capstone: false,
        usage_limit: "session"
    },
    emberlash_retaliation: {
        name_key: "talent_draevi_emberlash_retaliation-u",
        rule_text_key: "talent_draevi_emberlash_retaliation_rules-u",
        skills: "",
        prerequisite: [ "instinctive_counter" ],
        tier: 3,
        cost: 30,
        capstone: false,
        usage_limit: "session"
    },
    legacy_reforged: {
        name_key: "talent_draevi_legacy_reforged-u",
        rule_text_key: "talent_draevi_legacy_reforged_rules-u",
        skills: "",
        prerequisite: "",
        prerequisiteAny: { tier: 2, count: 2 },
        tier: 3,
        cost: 30,
        capstone: false,
        usage_limit: "session"
    },
    pathfinders_edge: {
        name_key: "talent_draevi_pathfinders_edge-u",
        rule_text_key: "talent_draevi_pathfinders_edge_rules-u",
        skills: "",
		affected_skill: [ "navigate", "track" ],
        prerequisite: [ "hardened_trailwalker", "veins_of_stone" ],
        tier: 3,
        cost: 30,
        capstone: false,
        usage_limit: "session"
    },
    spirit_touched_mastery: {
        name_key: "talent_draevi_spirit_touched_mastery-u",
        rule_text_key: "talent_draevi_spirit_touched_mastery_rules-u",
        skills: "",
		affected_skill: [ "magic_summoning", "spirit_lore" ],
        prerequisite: [ "echo_binders_rite" ],
        tier: 3,
        cost: 30,
        capstone: false,
        usage_limit: "session"
    },
    spiritual_vanguard: {
        name_key: "talent_draevi_spiritual_vanguard-u",
        rule_text_key: "talent_draevi_spiritual_vanguard_rules-u",
        skills: "",
        prerequisite: [ "scent_the_shift", "tales_etched_in_horn" ],
        tier: 3,
        cost: 30,
        capstone: false,
        usage_limit: "session"
    },
    wild_tamers_gaze: {
        name_key: "talent_draevi_wild_tamers_gaze-u",
        rule_text_key: "talent_draevi_wild_tamers_gaze_rules-u",
        skills: "",
		affected_skill: [ "animalhandling", "spirit_lore" ],
        prerequisite: [ "ancestors_pulse", "echo_binders_rite" ],
        tier: 3,
        cost: 30,
        capstone: false,
        usage_limit: "session"
    },
    ancestral_mirror: {
        name_key: "talent_draevi_ancestral_mirror-u",
        rule_text_key: "talent_draevi_ancestral_mirror_rules-u",
        skills: "",
		affected_skill: [ "magic_summoning", "spirit_lore" ],
        prerequisite: [ "echo_binders_rite", "spirit_touched_mastery" ],
        tier: 4,
        cost: 40,
        capstone: true,
        usage_limit: "session"
    },
    echo_flame_warden: {
        name_key: "talent_draevi_echo_flame_warden-u",
        rule_text_key: "talent_draevi_echo_flame_warden_rules-u",
        skills: "",
		affected_stat: [ "con", "pow" ],
        prerequisite: [ "spiritual_vanguard", "veins_of_stone" ],
        tier: 4,
        cost: 40,
        capstone: true,
        usage_limit: "session"
    },
    path_of_the_remembered: {
        name_key: "talent_draevi_path_of_the_remembered-u",
        rule_text_key: "talent_draevi_path_of_the_remembered_rules-u",
        skills: "",
		affected_skill: [ "perception", "survival_urban", "survival_wilderness" ],
		affected_stat: "pow",
        prerequisite: [ "ancestors_pulse", "tales_etched_in_horn" ],
        tier: 4,
        cost: 40,
        capstone: true,
        usage_limit: "session"
    },
    soul_of_the_wild_hunt: {
        name_key: "talent_draevi_soul_of_the_wild_hunt-u",
        rule_text_key: "talent_draevi_soul_of_the_wild_hunt_rules-u",
        skills: "",
		affected_skill: [ "stealth", "track" ],
		affected_skill_group: "combat_melee",
        prerequisite: [ "emberlash_retaliation", "pathfinders_edge" ],
        tier: 4,
        cost: 40,
        capstone: true,
        usage_limit: "session"
    }
   },
  feran: {
    predators_focus: {
      name_key:  "talent_feran_predators_focus-u",
      rule_text_key: "talent_feran_predators_focus_rules-u",
      skills: "",
	  affected_skill: [ "insight", "perception" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    razorstep_pounce: {
      name_key:  "talent_feran_razorstep_pounce-u",
      rule_text_key: "talent_feran_razorstep_pounce_rules-u",
      skills: "",
	  affected_skill: "unarmed",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    scavengers_instinct: {
      name_key:  "talent_feran_scavengers_instinct-u",
      rule_text_key: "talent_feran_scavengers_instinct_rules-u",
      skills: [ "navigate", "streetwise", "survival_urban" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    scent_of_the_kill: {
      name_key:  "talent_feran_scent_of_the_kill-u",
      rule_text_key: "talent_feran_scent_of_the_kill_rules-u",
      skills: "",
	  affected_skill: [ "insight", "streetwise", "track" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "scene"
    },
    silent_leap: {
      name_key:  "talent_feran_silent_leap-u",
      rule_text_key: "talent_feran_silent_leap_rules-u",
      skills: "",
	  affected_skill: [ "athletics", "stealth" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    threadrunners_poise: {
      name_key:  "talent_feran_threadrunners_poise-u",
      rule_text_key: "talent_feran_threadrunners_poise_rules-u",
      skills: "",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    wallrunners_step: {
      name_key:  "talent_feran_wallrunners_step-u",
      rule_text_key: "talent_feran_wallrunners_step_rules-u",
      skills: "",
	  affected_skill: [ "athletics", "coordination" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    ambush_instincts: {
      name_key:  "talent_feran_ambush_instincts-u",
      rule_text_key: "talent_feran_ambush_instincts_rules-u",
      skills: "",
      prerequisite: "",
      prerequisiteAny: { tier: 1, count: 1 },
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "scene"
    },
    bloodrushed_recovery: {
      name_key:  "talent_feran_bloodrushed_recovery-u",
      rule_text_key: "talent_feran_bloodrushed_recovery_rules-u",
      skills: "",
	  affected_skill: "dodge",
      prerequisite: "",
      prerequisiteAny: { tier: 1, count: 1 },
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    pack_sense_reversal: {
      name_key:  "talent_feran_pack_sense_reversal-u",
      rule_text_key: "talent_feran_pack_sense_reversal_rules-u",
      skills: "",
	  affected_skill: [ "dodge", "unarmed" ],
      prerequisite: [ "predators_focus", "scavengers_instinct" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    pounce_and_break: {
      name_key:  "talent_feran_pounce_and_break-u",
      rule_text_key: "talent_feran_pounce_and_break_rules-u",
      skills: "",
	  affected_skill: "dodge",
      prerequisite: [ "razorstep_pounce" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    predators_patience: {
      name_key:  "talent_feran_predators_patience-u",
      rule_text_key: "talent_feran_predators_patience_rules-u",
      skills: "",
	  affected_skill: "stealth",
      prerequisite: [ "predators_focus", "silent_leap" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    scentlock_tactics: {
      name_key:  "talent_feran_scentlock_tactics-u",
      rule_text_key: "talent_feran_scentlock_tactics_rules-u",
      skills: "",
	  affected_skill: [ "insight", "streetwise" ],
      prerequisite: [ "scent_of_the_kill" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    threadwalkers_rhythm: {
      name_key:  "talent_feran_threadwalkers_rhythm-u",
      rule_text_key: "talent_feran_threadwalkers_rhythm_rules-u",
      skills: "",
	  affected_skill: "athletics",
      prerequisite: [ "threadrunners_poise", "wallrunners_step" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    apex_reflex: {
      name_key:  "talent_feran_apex_reflex-u",
      rule_text_key: "talent_feran_apex_reflex_rules-u",
      skills: "",
	  affected_skill: "dodge",
	  affected_skill_group: "combat_melee",
      prerequisite: [ "pack_sense_reversal" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    battle_rush_clarity: {
      name_key:  "talent_feran_battle_rush_clarity-u",
      rule_text_key: "talent_feran_battle_rush_clarity_rules-u",
      skills: "",
      prerequisite: [ "bloodrushed_recovery" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    chain_strike_instinct: {
      name_key:  "talent_feran_chain_strike_instinct-u",
      rule_text_key: "talent_feran_chain_strike_instinct_rules-u",
      skills: "",
	  affected_skill_group: "combat_melee",
      prerequisite: [ "pounce_and_break", "stalkers_cascade" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    pack_alphas_demand: {
      name_key:  "talent_feran_pack_alphas_demand-u",
      rule_text_key: "talent_feran_pack_alphas_demand_rules-u",
      skills: "",
	  affected_skill: "dodge",
	  affected_skill_group: "combat_melee",
      prerequisite: [ "pack_sense_reversal" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    predators_terrain: {
      name_key:  "talent_feran_predators_terrain-u",
      rule_text_key: "talent_feran_predators_terrain_rules-u",
      skills: "",
	  affected_skill: [ "athletics", "dodge" ],
      prerequisite: [ "threadwalkers_rhythm" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    stalkers_cascade: {
      name_key:  "talent_feran_stalkers_cascade-u",
      rule_text_key: "talent_feran_stalkers_cascade_rules-u",
      skills: "",
      prerequisite: [ "pounce_and_break", "predators_patience" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    ghostclaw_alpha: {
      name_key: "talent_feran_ghostclaw_alpha-u",
      rule_text_key: "talent_feran_ghostclaw_alpha_rules-u",
      skills: "",
	  affected_skill: "stealth",
	  affected_skill_group: "combat_melee",
      prerequisite: [ "apex_reflex", "stalkers_cascade" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    pack_memory_living_instinct: {
      name_key: "talent_feran_pack_memory_living_instinct-u",
      rule_text_key: "talent_feran_pack_memory_living_instinct_rules-u",
      skills: "",
	  affected_skill: [ "athletics", "dodge" ],
      prerequisite: [ "pack_alphas_demand", "predators_terrain" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    pulse_lock_drive: {
      name_key: "talent_feran_pulse_lock_drive-u",
      rule_text_key: "talent_feran_pulse_lock_drive_rules-u",
      skills: "",
      prerequisite: [ "chain_strike_instinct", "stalkers_cascade" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    threadbound_mastery: {
      name_key: "talent_feran_threadbound_mastery-u",
      rule_text_key: "talent_feran_threadbound_mastery_rules-u",
      skills: "",
      prerequisite: [ "predators_terrain" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    }
  },
  human : {
    battle_tested_gut: {
      name_key:  "talent_human_battle_tested_gut-u",
      rule_text_key: "talent_human_battle_tested_gut_rules-u",
      skills: "",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    hard_lesson: {
      name_key:  "talent_human_hard_lesson-u",
      rule_text_key: "talent_human_hard_lesson_rules-u",
      skills: "",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    instinct_over_training: {
      name_key:  "talent_human_instinct_over_training-u",
      rule_text_key: "talent_human_instinct_over_training_rules-u",
      skills: "",
	  affected_stat: "edu",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    makeshift_medic: {
      name_key:  "talent_human_makeshift_medic-u",
      rule_text_key: "talent_human_makeshift_medic_rules-u",
      skills: "",
	  affected_skill: "first_aid",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    no_stranger_to_pain: {
      name_key:  "talent_human_no_stranger_to_pain-u",
      rule_text_key: "talent_human_no_stranger_to_pain_rules-u",
      skills: "",
	  affected_stat: "con",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    quick_fixer: {
      name_key:  "talent_human_quick_fixer-u",
      rule_text_key: "talent_human_quick_fixer_rules-u",
      skills: [ "electronics", "mechanics", "slicing" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    skilled_focus: {
	  /* Handled in sheet worker */
      name_key:  "talent_human_skilled_focus-u",
      rule_text_key: "talent_human_skilled_focus_rules-u",
      skills: "",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    social_versatility: {
      name_key:  "talent_human_social_versatility-u",
      rule_text_key: "talent_human_social_versatility_rules-u",
      skills: "",
	  affected_skill: [ "charm", "deception", "persuade" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    cross_trained: {
	  /* Handled in sheet worker */
      name_key:  "talent_human_cross_trained-u",
      rule_text_key: "talent_human_cross_trained_rules-u",
      skills: "",
      prerequisite: [ "quick_learner", "skilled_focus" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    defiant_resilience: {
      name_key:  "talent_human_defiant_resilience-u",
      rule_text_key: "talent_human_defiant_resilience_rules-u",
      skills: "",
	  affected_skill: "insight",
	  affected_stat: "pow",
      prerequisite: [ "no_stranger_to_pain" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    improvised_tools: {
      name_key:  "talent_human_improvised_tools-u",
      rule_text_key: "talent_human_improvised_tools_rules-u",
      skills: "",
	  affected_skill: [ "electronics", "mechanics", "slicing" ],
      prerequisite: [ "quick_fixer" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    lucky_timing: {
      name_key:  "talent_human_lucky_timing-u",
      rule_text_key: "talent_human_lucky_timing_rules-u",
      skills: "",
      prerequisite: [ "skilled_focus", "social_versatility" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    quick_learner: {
      name_key:  "talent_human_quick_learner-u",
      rule_text_key: "talent_human_quick_learner_rules-u",
      skills: "",
      prerequisite: [ "battle_tested_gut", "hard_lesson", "instinct_over_training", "makeshift_medic", "no_stranger_to_pain", "quick_fixer", "skilled_focus", "social_versatility" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    situational_awareness: {
      name_key:  "talent_human_situational_awareness-u",
      rule_text_key: "talent_human_situational_awareness_rules-u",
      skills: "",
	  affected_skill: [ "insight", "listen", "perception" ],
      prerequisite: [ "battle_tested_gut", "instinct_over_training" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    spontaneous_strategist: {
      name_key:  "talent_human_spontaneous_strategist-u",
      rule_text_key: "talent_human_spontaneous_strategist_rules-u",
      skills: "",
	  affected_skill: [ "dodge", "insight", "persuade" ],
      prerequisite: [ "hard_lesson" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "scene"
    },
    break_the_pattern: {
      name_key:  "talent_human_break_the_pattern-u",
      rule_text_key: "talent_human_break_the_pattern_rules-u",
      skills: "",
      prerequisite: [ "lucky_timing", "social_versatility" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    chain_of_luck: {
      name_key:  "talent_human_chain_of_luck-u",
      rule_text_key: "talent_human_chain_of_luck_rules-u",
      skills: "",
      prerequisite: [ "hard_lesson", "lucky_timing" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    dig_deep: {
      name_key:  "talent_human_dig_deep-u",
      rule_text_key: "talent_human_dig_deep_rules-u",
      skills: "",
	  affected_stat: "con",
      prerequisite: [ "defiant_resilience" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    just_enough_prep: {
      name_key:  "talent_human_just_enough_prep-u",
      rule_text_key: "talent_human_just_enough_prep_rules-u",
      skills: "",
      prerequisite: [ "improvised_tools", "situational_awareness" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    momentum_shift: {
      name_key:  "talent_human_momentum_shift-u",
      rule_text_key: "talent_human_momentum_shift_rules-u",
      skills: "",
      prerequisite: [ "quick_learner", "spontaneous_strategist" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    pull_from_memory: {
      name_key:  "talent_human_pull_from_memory-u",
      rule_text_key: "talent_human_pull_from_memory_rules-u",
      skills: "",
	  affected_skill: "history",
	  affected_skill_group: [ "lore", "magic" ],
      prerequisite: [ "instinct_over_training" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    luck_bends_for_me: {
      name_key: "talent_human_luck_bends_for_me-u",
      rule_text_key: "talent_human_luck_bends_for_me_rules-u",
      skills: "",
	  affected_stat: "luck",
      prerequisite: [ "chain_of_luck", "hard_lesson" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    master_of_none: {
      name_key: "talent_human_master_of_none-u",
      rule_text_key: "talent_human_master_of_none_rules-u",
      skills: "",
      prerequisite: [ "cross_trained", "skilled_focus" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: ""
    },
    tactical_improviser: {
      name_key: "talent_human_tactical_improviser-u",
      rule_text_key: "talent_human_tactical_improviser_rules-u",
      skills: "",
      prerequisite: [ "just_enough_prep", "momentum_shift" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    unshakable_focus: {
      name_key: "talent_human_unshakable_focus-u",
      rule_text_key: "talent_human_unshakable_focus_rules-u",
      skills: "",
	  affected_stat: "pow",
      prerequisite: [ "defiant_resilience", "dig_deep" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    }
  },
  khadra: {
    anchorpoint: {
      name_key:  "talent_khadra_anchorpoint-u",
      rule_text_key: "talent_khadra_anchorpoint_rules-u",
      skills: "",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    legacy_of_iron: {
      name_key:  "talent_khadra_legacy_of_iron-u",
      rule_text_key: "talent_khadra_legacy_of_iron_rules-u",
      skills: [ "first_aid", "mechanics", "security" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    measured_advance: {
      name_key:  "talent_khadra_measured_advance-u",
      rule_text_key: "talent_khadra_measured_advance_rules-u",
      skills: "",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "scene"
    },
    oathbound_grit: {
      name_key:  "talent_khadra_oathbound_grit-u",
      rule_text_key: "talent_khadra_oathbound_grit_rules-u",
      skills: "",
	  affected_stat: [ "con", "pow" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    slow_to_bleed: {
      name_key:  "talent_khadra_slow_to_bleed-u",
      rule_text_key: "talent_khadra_slow_to_bleed_rules-u",
      skills: "",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    steady_as_stone: {
      name_key:  "talent_khadra_steady_as_stone-u",
      rule_text_key: "talent_khadra_steady_as_stone_rules-u",
      skills: "",
	  affected_skill: [ "athletics", "coordination" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    still_as_judgment: {
      name_key:  "talent_khadra_still_as_judgment-u",
      rule_text_key: "talent_khadra_still_as_judgment_rules-u",
      skills: "",
	  affected_skill: [ "etiquette_military", "insight", "interrogation" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    unbreakable_focus: {
      name_key:  "talent_khadra_unbreakable_focus-u",
      rule_text_key: "talent_khadra_unbreakable_focus_rules-u",
      skills: "",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    ancestral_echo_guard: {
      name_key:  "talent_khadra_ancestral_echo_guard-u",
      rule_text_key: "talent_khadra_ancestral_echo_guard_rules-u",
      skills: "",
	  affected_skill: "arcana",
	  affected_stat: "pow",
      prerequisite: [ "unbreakable_focus" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "scene"
    },
    hold_the_line: {
      name_key:  "talent_khadra_hold_the_line-u",
      rule_text_key: "talent_khadra_hold_the_line_rules-u",
      skills: "",
	  affected_skill: "dodge",
	  affected_trait: "weight_of_stone",
      prerequisite: [ "anchorpoint" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    oath_echo_discipline: {
      name_key:  "talent_khadra_oath_echo_discipline-u",
      rule_text_key: "talent_khadra_oath_echo_discipline_rules-u",
      skills: "",
	  affected_skill: [ "first_aid", "mechanics" ],
      prerequisite: [ "legacy_of_iron" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    path_of_the_immovable: {
      name_key:  "talent_khadra_path_of_the_immovable-u",
      rule_text_key: "talent_khadra_path_of_the_immovable_rules-u",
      skills: "",
	  affected_skill: "athletics",
	  affected_stat: "con",
      prerequisite: [ "anchorpoint", "steady_as_stone" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    rooted_in_purpose: {
      name_key:  "talent_khadra_rooted_in_purpose-u",
      rule_text_key: "talent_khadra_rooted_in_purpose_rules-u",
      skills: "",
      prerequisite: [ "steady_as_stone" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    shield_of_legacy: {
      name_key:  "talent_khadra_shield_of_legacy-u",
      rule_text_key: "talent_khadra_shield_of_legacy_rules-u",
      skills: "",
      prerequisite: [ "anchorpoint", "measured_advance" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "scene"
    },
    stonecut_precision: {
      name_key:  "talent_khadra_stonecut_precision-u",
      rule_text_key: "talent_khadra_stonecut_precision_rules-u",
      skills: "",
	  affected_skill_group: "combat_melee",
      prerequisite: [ "anchorpoint", "steady_as_stone" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    stonewalk_rhythm: {
      name_key:  "talent_khadra_stonewalk_rhythm-u",
      rule_text_key: "talent_khadra_stonewalk_rhythm_rules-u",
      skills: "",
	  affected_skill: "navigate",
      prerequisite: [ "measured_advance" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    weight_everlasting: {
      name_key:  "talent_khadra_weight_everlasting-u",
      rule_text_key: "talent_khadra_weight_everlasting_rules-u",
      skills: "",
	  affected_trait: "weight_of_stone",
      prerequisite: [ "anchorpoint" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: ""
    },
    echo_resonant_will: {
      name_key:  "talent_khadra_echo_resonant_will-u",
      rule_text_key: "talent_khadra_echo_resonant_will_rules-u",
      skills: "",
	  affected_skill: "arcana",
	  affected_stat: "pow",
      prerequisite: [ "ancestral_echo_guard" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    last_wall_protocol: {
      name_key:  "talent_khadra_last_wall_protocol-u",
      rule_text_key: "talent_khadra_last_wall_protocol_rules-u",
      skills: "",
	  affected_stat: "con",
      prerequisite: [ "hold_the_line", "rooted_in_purpose" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    legacy_chainstrike: {
      name_key:  "talent_khadra_legacy_chainstrike-u",
      rule_text_key: "talent_khadra_legacy_chainstrike_rules-u",
      skills: "",
      prerequisite: [ "rooted_in_purpose" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    resolve_unyielding: {
      name_key:  "talent_khadra_resolve_unyielding-u",
      rule_text_key: "talent_khadra_resolve_unyielding_rules-u",
      skills: "",
	  affected_stat: [ "con", "pow" ],
      prerequisite: [ "hold_the_line" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    stonewalk_continuum: {
      name_key:  "talent_khadra_stonewalk_continuum-u",
      rule_text_key: "talent_khadra_stonewalk_continuum_rules-u",
      skills: "",
	  affected_skill: [ "navigate", "survival_wilderness" ],
      prerequisite: [ "stonewalk_rhythm" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    stonewarden_tactician: {
      name_key:  "talent_khadra_stonewarden_tactician-u",
      rule_text_key: "talent_khadra_stonewarden_tactician_rules-u",
      skills: "",
      prerequisite: [ "shield_of_legacy" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "scene"
    },
    verdict_of_stone: {
      name_key:  "talent_khadra_verdict_of_stone-u",
      rule_text_key: "talent_khadra_verdict_of_stone_rules-u",
      skills: "",
	  affected_skill: [ "intimidate", "etiquette_military" ],
      prerequisite: [ "rooted_in_purpose" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    weight_makes_the_weapon: {
      name_key:  "talent_khadra_weight_makes_the_weapon-u",
      rule_text_key: "talent_khadra_weight_makes_the_weapon_rules-u",
      skills: "",
	  affected_skill_group: "combat_melee",
      prerequisite: [ "rooted_in_purpose" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    bastion_unyielding: {
      name_key:  "talent_khadra_bastion_unyielding-u",
      rule_text_key: "talent_khadra_bastion_unyielding_rules-u",
      skills: "",
      prerequisite: [ "last_wall_protocol", "resolve_unyielding" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    echo_of_the_first_stone: {
      name_key:  "talent_khadra_echo_of_the_first_stone-u",
      rule_text_key: "talent_khadra_echo_of_the_first_stone_rules-u",
      skills: "",
	  affected_stat: [ "con", "pow" ],
      prerequisite: [ "echo_resonant_will", "resolve_unyielding" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    oath_of_the_deep_hold: {
      name_key:  "talent_khadra_oath_of_the_deep_hold-u",
      rule_text_key: "talent_khadra_oath_of_the_deep_hold_rules-u",
      skills: "",
	  affected_skill: "dodge",
	  affected_trait: "weight_of_stone",
      prerequisite: [ "last_wall_protocol", "stonewarden_tactician" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    stone_sung_authority: {
      name_key:  "talent_khadra_stone_sung_authority-u",
      rule_text_key: "talent_khadra_stone_sung_authority_rules-u",
      skills: "",
	  affected_skill: [ "intimidate", "persuade" ],
      prerequisite: [ "stonewarden_tactician", "verdict_of_stone" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    }
  },
  kitsu: {
    aether_flick: {
      name_key:  "talent_kitsu_aether_flick-u",
      rule_text_key: "talent_kitsu_aether_flick_rules-u",
      skills: [ "magic_enchantment", "magic_illusion", "slicing" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    mask_of_the_moment: {
      name_key:  "talent_kitsu_mask_of_the_moment-u",
      rule_text_key: "talent_kitsu_mask_of_the_moment_rules-u",
      skills: "",
	  affected_skill: [ "charm", "deception", "disguise" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    pulse_trickster: {
      name_key:  "talent_kitsu_pulse_trickster-u",
      rule_text_key: "talent_kitsu_pulse_trickster_rules-u",
      skills: "",
	  affected_skill: [ "deception", "slicing" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    streetwise_instincts: {
      name_key:  "talent_kitsu_streetwise_instincts-u",
      rule_text_key: "talent_kitsu_streetwise_instincts_rules-u",
      skills: [ "insight", "stealth", "streetwise" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    twitch_reflex: {
      name_key:  "talent_kitsu_twitch_reflex-u",
      rule_text_key: "talent_kitsu_twitch_reflex_rules-u",
      skills: "",
	  affected_skill: [ "dodge", "slicing" ],
	  affected_stat: "initiative",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "scene"
    },
    veil_sniff: {
      name_key:  "talent_kitsu_veil_sniff-u",
      rule_text_key: "talent_kitsu_veil_sniff_rules-u",
      skills: "",
	  affected_skill: [ "arcana", "spirit_lore" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    whisperstep: {
      name_key:  "talent_kitsu_whisperstep-u",
      rule_text_key: "talent_kitsu_whisperstep_rules-u",
      skills: "",
	  affected_skill: "stealth",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    flicker_edge_movement: {
      name_key:  "talent_kitsu_flicker_edge_movement-u",
      rule_text_key: "talent_kitsu_flicker_edge_movement_rules-u",
      skills: "",
	  affected_skill: "dodge",
      prerequisite: [ "streetwise_instincts", "twitch_reflex" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "scene"
    },
    foxs_masquerade: {
      name_key:  "talent_kitsu_foxs_masquerade-u",
      rule_text_key: "talent_kitsu_foxs_masquerade_rules-u",
      skills: "",
	  affected_skill: [ "deception", "disguise", "magic_illusion" ],
      prerequisite: [ "mask_of_the_moment", "pulse_trickster" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    hollow_sound: {
      name_key:  "talent_kitsu_hollow_sound-u",
      rule_text_key: "talent_kitsu_hollow_sound_rules-u",
      skills: "",
	  affected_skill: "stealth",
	  affected_skill_group: "combat_melee",
      prerequisite: [ "whisperstep" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    nerve_hijack: {
      name_key:  "talent_kitsu_nerve_hijack-u",
      rule_text_key: "talent_kitsu_nerve_hijack_rules-u",
      skills: "",
	  affected_skill: "slicing",
      prerequisite: [ "aether_flick" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: ""
    },
    sensory_overclock: {
      name_key:  "talent_kitsu_sensory_overclock-u",
      rule_text_key: "talent_kitsu_sensory_overclock_rules-u",
      skills: "",
	  affected_skill: [ "insight", "perception" ],
      prerequisite: [ "streetwise_instincts", "twitch_reflex" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    urban_echo: {
      name_key:  "talent_kitsu_urban_echo-u",
      rule_text_key: "talent_kitsu_urban_echo_rules-u",
      skills: "",
	  affected_skill: [ "athletics", "coordination", "slicing" ],
      prerequisite: [ "streetwise_instincts", "whisperstep" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    blurring_veil: {
      name_key: "talent_kitsu_blurring_veil-u",
      rule_text_key: "talent_kitsu_blurring_veil_rules-u",
      skills: "",
	  affected_skill: "dodge",
      prerequisite: [ "hollow_sound", "one_breath_casting" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    coded_whisper: {
      name_key: "talent_kitsu_coded_whisper-u",
      rule_text_key: "talent_kitsu_coded_whisper_rules-u",
      skills: "",
	  affected_skill: [ "magic_enchantment", "persuade", "slicing" ],
      prerequisite: [ "foxs_masquerade", "pulse_trickster" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    mirror_nerve: {
      name_key: "talent_kitsu_mirror_nerve-u",
      rule_text_key: "talent_kitsu_mirror_nerve_rules-u",
      skills: "",
	  affected_skill: [ "slicing", "unarmed" ],
	  affected_skill_group: "magic",
      prerequisite: [ "foxs_masquerade", "one_breath_casting" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    one_breath_casting: {
      name_key: "talent_kitsu_one_breath_casting-u",
      rule_text_key: "talent_kitsu_one_breath_casting_rules-u",
      skills: "",
	  affected_skill: [ "magic_alteration", "magic_enchantment", "magic_illusion" ],
      prerequisite: [ "aether_flick", "foxs_masquerade" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    phase_residue: {
      name_key: "talent_kitsu_phase_residue-u",
      rule_text_key: "talent_kitsu_phase_residue_rules-u",
      skills: "",
	  affected_skill: [ "dodge", "stealth" ],
      prerequisite: [ "blurring_veil", "flicker_edge_movement" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    shadow_map: {
      name_key: "talent_kitsu_shadow_map-u",
      rule_text_key: "talent_kitsu_shadow_map_rules-u",
      skills: "",
	  affected_skill: [ "navigation", "slicing", "stealth" ],
      prerequisite: [ "sensory_overclock", "streetwise_instincts" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    slipframe_trigger: {
      name_key: "talent_kitsu_slipframe_trigger-u",
      rule_text_key: "talent_kitsu_slipframe_trigger_rules-u",
      skills: "",
	  affected_skill: [ "deception", "magic_illusion", "stealth" ],
      prerequisite: [ "flicker_edge_movement", "pulse_trickster" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    mask_of_the_hunt: {
      name_key: "talent_kitsu_mask_of_the_hunt-u",
      rule_text_key: "talent_kitsu_mask_of_the_hunt_rules-u",
      skills: "",
	  affected_skill: [ "insight", "slicing", "stealth" ],
      prerequisite: ["blurring_veil", "shadow_map"],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    nine_lives_protocol: {
      name_key: "talent_kitsu_nine_lives_protocol-u",
      rule_text_key: "talent_kitsu_nine_lives_protocol_rules-u",
      skills: "",
	  affected_skill: "slicing",
	  affected_skill_group: [ "combat", "magic" ],
      prerequisite: ["blurring_veil", "one_breath_casting"],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    rewired_pulse: {
      name_key: "talent_kitsu_rewired_pulse-u",
      rule_text_key: "talent_kitsu_rewired_pulse_rules-u",
      skills: "",
      affected_skill: "slicing",
	  affected_skill_group: [ "magic" ],
      prerequisite: ["coded_whisper", "mirror_nerve"],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    tailwind_gambit: {
      name_key: "talent_kitsu_tailwind_gambit-u",
      rule_text_key: "talent_kitsu_tailwind_gambit_rules-u",
      skills: "",
      prerequisite: ["foxs_masquerade", "shadow_map"],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    }
  },
  lyranni: {
    aether_override: {
      name_key: "talent_lyranni_aether_override-u",
      rule_text_key: "talent_lyranni_aether_override_rules-u",
      skills: "",
	  affected_skill: [ "electronics", "mechanics", "slicing" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    echo_in_the_veins: {
      name_key: "talent_lyranni_echo_in_the_veins-u",
      rule_text_key: "talent_lyranni_echo_in_the_veins_rules-u",
      skills: [ "insight", "perform_acting", "perform_dance", "perform_impersonation", "perform_instrument", "perform_vocal", "streetwise" ],
	  affected_skill: [ ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    glimmerstep: {
      name_key: "talent_lyranni_glimmerstep-u",
      rule_text_key: "talent_lyranni_glimmerstep_rules-u",
      skills: "",
	  affected_skill: [ "arcana", "stealth" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "scene"
    },
    legacy_spark: {
      name_key: "talent_lyranni_legacy_spark-u",
      rule_text_key: "talent_lyranni_legacy_spark_rules-u",
      skills: "",
	  affected_skill: [ "arcana", "etiquette_lyranni", "occult_lore"],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    resonant_poise: {
      name_key: "talent_lyranni_resonant_poise-u",
      rule_text_key: "talent_lyranni_resonant_poise_rules-u",
      skills: "",
	  affected_skill: [ "charm", "etiquette_high_society", "etiquette_lyranni" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    social_ghost: {
      name_key: "talent_lyranni_social_ghost-u",
      rule_text_key: "talent_lyranni_social_ghost_rules-u",
      skills: "",
	  affected_skill: [ "charm", "intimidate", "persuade" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    threadwalker: {
      name_key: "talent_lyranni_threadwalker-u",
      rule_text_key: "talent_lyranni_threadwalker_rules-u",
      skills: [ "arcana", "occult_lore", "spirit_lore" ],
	  affected_skill: [ "arcana", "occult_lore", "spirit_lore" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    veil_blooded_sense: {
      name_key: "talent_lyranni_veil_blooded_sense-u",
      rule_text_key: "talent_lyranni_veil_blooded_sense_rules-u",
      skills: "",
	  affected_skill: [ "arcana", "spirit_lore" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    veilsight: {
      name_key: "talent_lyranni_veilsight-u",
      rule_text_key: "talent_lyranni_veilsight_rules-u",
      skills: "",
	  affected_skill: [ "arcana", "spirit_lore" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "scene"
    },
    ancestral_resonance: {
      name_key: "talent_lyranni_ancestral_resonance-u",
      rule_text_key: "talent_lyranni_ancestral_resonance_rules-u",
      skills: "",
	  affected_skill: [ "arcana", "occult_lore", "spirit_lore" ],
      prerequisite: [ "legacy_spark" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    illuminated_touch: {
      name_key: "talent_lyranni_illuminated_touch-u",
      rule_text_key: "talent_lyranni_illuminated_touch_rules-u",
      skills: "",
	  affected_skill: [ "insight", "spirit_lore" ],
      prerequisite: [ "threadwalker", "veilsight" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    memory_bound_echo: {
      name_key: "talent_lyranni_memory_bound_echo-u",
      rule_text_key: "talent_lyranni_memory_bound_echo_rules-u",
      skills: "",
	  affected_skill: [ "arcana", "occult_lore", "spirit_lore" ],
      prerequisite: [ "legacy_spark" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    rite_bound: {
      name_key: "talent_lyranni_rite_bound-u",
      rule_text_key: "talent_lyranni_rite_bound_rules-u",
      skills: "",
	  affected_skill_group: "magic",
      prerequisite: [ "veil_blooded_sense" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    spirit_favored: {
      name_key: "talent_lyranni_spirit_favored-u",
      rule_text_key: "talent_lyranni_spirit_favored_rules-u",
      skills: "",
	  affected_skill: [ "charm", "insight", "persuade" ],
      prerequisite: [ "veilsight" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    veil_dancer: {
      name_key: "talent_lyranni_veil_dancer-u",
      rule_text_key: "talent_lyranni_veil_dancer_rules-u",
      skills: "",
	  affected_skill: [ "deception", "stealth" ],
	  affected_skill_group: "perform",
      prerequisite: [ "echo_in_the_veins" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    veilsplice: {
      name_key: "talent_lyranni_veilsplice-u",
      rule_text_key: "talent_lyranni_veilsplice_rules-u",
      skills: "",
	  affected_skill: [ "electronics", "slicing" ],
      prerequisite: [ "aether_override" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    whispers_beyond: {
      name_key: "talent_lyranni_whispers_beyond-u",
      rule_text_key: "talent_lyranni_whispers_beyond_rules-u",
      skills: "",
      prerequisite: [ "veilsight" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    words_like_silk: {
      name_key: "talent_lyranni_words_like_silk-u",
      rule_text_key: "talent_lyranni_words_like_silk_rules-u",
      skills: "",
	  affected_skill: [ "charm", "persuade" ],
      prerequisite: [ "social_ghost" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    blood_rite_channeling: {
      name_key: "talent_lyranni_blood_rite_channeling-u",
      rule_text_key: "talent_lyranni_blood_rite_channeling_rules-u",
      skills: "",
	  affected_stat: "strain",
      prerequisite: "",
	  prerequisiteAny: { tier: 2, count: 1 },
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    echo_binding: {
      name_key: "talent_lyranni_echo_binding-u",
      rule_text_key: "talent_lyranni_echo_binding_rules-u",
      skills: "",
	  affected_skill: [ "arcana", "perception" ],
	  affected_skill_group: "magic",
      prerequisite: [ "memory_bound_echo", "rite_bound" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    lyranni_discipline: {
      name_key: "talent_lyranni_lyranni_discipline-u",
      rule_text_key: "talent_lyranni_lyranni_discipline_rules-u",
      skills: "",
      prerequisite: "",
	  prerequisiteAny: { tier: 2, count: 1 },
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    shadow_echo_step: {
      name_key: "talent_lyranni_shadow_echo_step-u",
      rule_text_key: "talent_lyranni_shadow_echo_step_rules-u",
      skills: "",
	  affected_skill: [ "dodge", "stealth" ],
      prerequisite: [ "glimmerstep", "veil_dancer" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "scene"
    },
    subtle_authority: {
      name_key: "talent_lyranni_subtle_authority-u",
      rule_text_key: "talent_lyranni_subtle_authority_rules-u",
      skills: "",
	  affected_skill: [ "charm", "etiquette_high_society" ],
	  affected_skill_group: "perform",
      prerequisite: [ "social_ghost" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    true_veilsight: {
      name_key: "talent_lyranni_true_veilsight-u",
      rule_text_key: "talent_lyranni_true_veilsight_rules-u",
      skills: "",
	  affected_skill: [ "arcana", "spirit_lore" ],
      prerequisite: [ "veilsight" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "scene"
    },
    veil_laced_command: {
      name_key: "talent_lyranni_veil_laced_command-u",
      rule_text_key: "talent_lyranni_veil_laced_command_rules-u",
      skills: "",
	  affected_skill: [ "intimidate", "persuade" ],
      prerequisite: [ "spirit_favored", "words_like_silk" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "scene"
    },
    breath_of_the_veil: {
      name_key: "talent_lyranni_breath_of_the_veil-u",
      rule_text_key: "talent_lyranni_breath_of_the_veil_rules-u",
      skills: "",
	  affected_skill: [ "arcana", "magic_enchantment", "magic_illusion", "spirit_lore" ],
      prerequisite: [ "true_veilsight" ],
      prerequisiteAny: { tier: 3, count: 1 },
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    echo_of_elegance: {
      name_key: "talent_lyranni_echo_of_elegance-u",
      rule_text_key: "talent_lyranni_echo_of_elegance_rules-u",
      name: "Echo of Elegance",
      description: "Once per session, ignore one penalty die on a social roll and gain a bonus die instead. You may also automatically succeed on one opposed Charm or Performance contest against a neutral or friendly target.",
      skills: "",
	  affected_skill: "charm",
	  affected_skill_group: "perform",
      prerequisite: [ "subtle_authority" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    veil_linked_will: {
      name_key: "talent_lyranni_veil_linked_will-u",
      rule_text_key: "talent_lyranni_veil_linked_will_rules-u",
      skills: "",
      prerequisite: [ "lyranni_discipline" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    voice_of_the_ancestors: {
      name_key: "talent_lyranni_voice_of_the_ancestors-u",
      rule_text_key: "talent_lyranni_voice_of_the_ancestors_rules-u",
      skills: "",
	  affected_skill_group: [ "magic", "social" ],
      prerequisiteAll: [ "ancestral_resonance", "spirit_favored" ],
      prerequisite: "",
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    }
  },
  veyra: {
    cache_sense: {
      name_key: "talent_veyra_cache_sense-u",
      rule_text_key: "talent_veyra_cache_sense_rules-u",
	  skills: "",
	  affected_skill: [ "mechanics", "survival_urban" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    circuit_whispers: {
      name_key: "talent_veyra_circuit_whispers-u",
      rule_text_key: "talent_veyra_circuit_whispers_rules-u",
      skills: "",
	  affected_skill: [ "electronics", "mechanics" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    echo_sense: {
      name_key: "talent_veyra_echo_sense-u",
      rule_text_key: "talent_veyra_echo_sense_rules-u",
      skills: "",
	  affected_skill: [ "listen", "perception" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    mask_the_signal: {
      name_key: "talent_veyra_mask_the_signal-u",
      rule_text_key: "talent_veyra_mask_the_signal_rules-u",
      skills: "",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "scene"
    },
    no_footprints: {
      name_key: "talent_veyra_no_footprints-u",
      rule_text_key: "talent_veyra_no_footprints_rules-u",
      skills: "",
	  affected_skill: "stealth",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    patchwork_fixer: {
      name_key: "talent_veyra_patchwork_fixer-u",
      rule_text_key: "talent_veyra_patchwork_fixer_rules-u",
      skills: "",
	  affected_skill: [ "electronics", "mechanics" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    reflex_map: {
      name_key: "talent_veyra_reflex_map-u",
      rule_text_key: "talent_veyra_reflex_map_rules-u",
      skills: "",
	  affected_skill: [ "listen", "perception" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    signal_ghost: {
      name_key: "talent_veyra_signal_ghost-u",
      rule_text_key: "talent_veyra_signal_ghost_rules-u",
      skills: "",
	  affected_skill: [ "security", "slicing" ],
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: "session"
    },
    slip_between: {
      name_key: "talent_veyra_slip_between-u",
      rule_text_key: "talent_veyra_slip_between_rules-u",
      skills: "",
	  affected_skill: "stealth",
      prerequisite: "",
      tier: 1,
      cost: 10,
      capstone: false,
      usage_limit: ""
    },
    battlefield_sync: {
      name_key: "talent_veyra_battlefield_sync-u",
      rule_text_key: "talent_veyra_battlefield_sync_rules-u",
      skills: "",
	  affected_skill: [ "listen", "perception" ],
      prerequisite: [ "reflex_map" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "scene"
    },
    echo_map_recall: {
      name_key: "talent_veyra_echo_map_recall-u",
      rule_text_key: "talent_veyra_echo_map_recall_rules-u",
      skills: "",
	  affected_skill: "perception",
      prerequisite: [ "echo_sense" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "scene"
    },
    nocturne_optimizer: {
      name_key: "talent_veyra_nocturne_optimizer-u",
      rule_text_key: "talent_veyra_nocturne_optimizer_rules-u",
      skills: "",
	  affected_skill: [ "electronics", "mechanics", "stealth" ],
      prerequisite: [ "echo_sense" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "scene"
    },
    overclock_instinct: {
      name_key: "talent_veyra_overclock_instinct-u",
      rule_text_key: "talent_veyra_overclock_instinct_rules-u",
      skills: "",
	  affected_skill: [ "electronics", "mechanics" ],
      prerequisite: [ "cache_sense" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "scene"
    },
    ping_and_pull: {
      name_key: "talent_veyra_ping_and_pull-u",
      rule_text_key: "talent_veyra_ping_and_pull_rules-u",
      skills: "",
	  affected_skill: [ "electronics", "slicing" ],
	  affected_skill_group: [ "magic" ],
      prerequisite: [ "circuit_whispers" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    salvage_sense: {
      name_key: "talent_veyra_salvage_sense-u",
      rule_text_key: "talent_veyra_salvage_sense_rules-u",
      skills: "",
      prerequisite: [ "cache_sense" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: ""
    },
    silent_cascade: {
      name_key: "talent_veyra_silent_cascade-u",
      rule_text_key: "talent_veyra_silent_cascade_rules-u",
      skills: "",
	  affected_skill: "stealth",
      prerequisite: [ "no_footprints" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "session"
    },
    vent_ghost: {
      name_key: "talent_veyra_vent_ghost-u",
      rule_text_key: "talent_veyra_vent_ghost_rules-u",
      skills: "",
	  affected_skill: "dodge",
      prerequisite: [ "circuit_whispers" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: "scene"
    },
    zero_trace_protocol: {
      name_key: "talent_veyra_zero_trace_protocol-u",
      rule_text_key: "talent_veyra_zero_trace_protocol_rules-u",
      skills: "",
	  affected_skill: [ "security", "slicing" ],
      prerequisite: [ "signal_ghost" ],
      tier: 2,
      cost: 20,
      capstone: false,
      usage_limit: ""
    },
    cachejack_protocol: {
      name_key: "talent_veyra_cachejack_protocol-u",
      rule_text_key: "talent_veyra_cachejack_protocol_rules-u",
      skills: "",
      prerequisite: [ "salvage_sense" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    dark_grid_savant: {
      name_key: "talent_veyra_dark_grid_savant-u",
      rule_text_key: "talent_veyra_dark_grid_savant_rules-u",
      skills: "",
	  affected_skill: "stealth",
      prerequisite: [ "nocturne_optimizer" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "scene"
    },
    echo_splice_reflex: {
      name_key: "talent_veyra_echo_splice_reflex-u",
      rule_text_key: "talent_veyra_echo_splice_reflex_rules-u",
      skills: "",
	  affected_skill: "listen",
      prerequisite: [ "battlefield_sync" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    echowire_scramble: {
      name_key: "talent_veyra_echowire_scramble-u",
      rule_text_key: "talent_veyra_echowire_scramble_rules-u",
      skills: "",
	  affected_skill: "electronics",
      prerequisite: [ "echo_map_recall" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    recursive_salvager: {
      name_key: "talent_veyra_recursive_salvager-u",
      rule_text_key: "talent_veyra_recursive_salvager_rules-u",
      skills: "",
      prerequisite: [ "overclock_instinct" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "scene"
    },
    signal_evasion_loop: {
      name_key: "talent_veyra_signal_evasion_loop-u",
      rule_text_key: "talent_veyra_signal_evasion_loop_rules-u",
      skills: "",
	  affected_skill: [ "security", "slicing" ],
      prerequisite: [ "zero_trace_protocol" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "session"
    },
    stealth_harmonic: {
      name_key: "talent_veyra_stealth_harmonic-u",
      rule_text_key: "talent_veyra_stealth_harmonic_rules-u",
      skills: "",
	  affected_skill: "stealth",
      prerequisite: [ "silent_cascade" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "scene"
    },
    thread_the_vents: {
      name_key: "talent_veyra_thread_the_vents-u",
      rule_text_key: "talent_veyra_thread_the_vents_rules-u",
      skills: "",
      prerequisite: [ "vent_ghost" ],
      tier: 3,
      cost: 30,
      capstone: false,
      usage_limit: "scene"
    },
    circuit_sovereign: {
      name_key:  "talent_veyra_circuit_sovereign-u",
      rule_text_key: "talent_veyra_circuit_sovereign_rules-u",
      skills: "",
      prerequisite: [ "cachejack_protocol" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    ghost_in_the_gears: {
      name_key:  "talent_veyra_ghost_in_the_gears-u",
      rule_text_key: "talent_veyra_ghost_in_the_gears_rules-u",
      skills: "",
      prerequisite: [ "recursive_salvager" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    neurospike_blur: {
      name_key:  "talent_veyra_neurospike_blur-u",
      rule_text_key: "talent_veyra_neurospike_blur_rules-u",
      skills: "",
      prerequisite: [ "dark_grid_savant" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    },
    silent_dominion: {
      name_key:  "talent_veyra_silent_dominion-u",
      rule_text_key: "talent_veyra_silent_dominion_rules-u",
      skills: "",
	  affected_skill: "stealth",
      prerequisite: [ "stealth_harmonic" ],
      tier: 4,
      cost: 40,
      capstone: true,
      usage_limit: "session"
    }
  }
};
